@echo off
echo Building Course Management System Frontend Bundle...
"C:\Users\Admin\AppData\Local\Programs\Antigravity IDE\resources\app\node_modules\@esbuild\win32-x64\esbuild.exe" src/main.jsx --bundle --outfile=dist/bundle.js --format=esm --external:react --external:react/jsx-runtime --external:react-dom --external:react-dom/client --external:react-router-dom --external:axios --external:lucide-react --loader:.jsx=jsx --loader:.js=jsx
echo Starting Frontend Web Server on http://localhost:3000/ ...
"C:\Program Files\PostgreSQL\18\pgAdmin 4\python\python.exe" -m http.server 3000
