# Generated by Django 5.2.17 on 2026-09-15 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Course code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('credits', models.PositiveSmallIntegerField(help_text='Must be between 1 and 6.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Credits')),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (weeks)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'instructor'], name='courses_is_acti_668e73_idx'), models.Index(fields=['code'], name='courses_code_fa42f1_idx')],
            },
        ),
    ]
